# Generated by Django 2.2.9 on 2020-04-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200321_2342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
