# Generated by Django 2.2.9 on 2020-04-30 04:04

import accounts.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200320_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=accounts.models.user_path),
        ),
    ]
