# Generated by Django 2.2.9 on 2020-04-30 08:17

from django.db import migrations
import imagekit.models.fields
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=post.models.photo_path),
        ),
    ]
